services:
  biss-ctf-back:
    image: biss-ctf-back:latest
    restart: always
    ports:
      - "8080:8080"
  biss-ctf-front:
    image: biss-ctf-front:latest
    restart: always
    ports:
      - "80:80"