services:
  biss-ctf-back:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: biss-ctf-back:latest
    restart: always
    volumes:
      - type: bind
        source: "[ABSOLUTE_PATH]"
        target: /mnt/resources
    environment:
      SPRING_CONFIG_LOCATION: file:///mnt/resources/
      CAPTCHA_PROPERTIES_LOCATION: file:///mnt/resources/captcha.properties
      SPRING_PROFILES_ACTIVE: container
#    Enable this for backend
#    ports:
#      - "8080:8080"
    depends_on:
      - python-executor
  biss-ctf-front:
    build:
      context: ../ctf-front
      dockerfile: Dockerfile
    image: biss-ctf-front:latest
    restart: always
#    Enable this for frontend
    ports:
      - "80:80"
    depends_on:
      - biss-ctf-back
  python-executor:
    image: python-runner
  #    Enable this for testing the python server
  #    ports:
  #      - "8000:8000"

# --- DB STUFF HERE ###
  db:
    image: postgres
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: YoudThinkItsAdminToo
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: YoudThinkItsAdmin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: YoudThinkItsAdminToo
    ports:
      - "8090:80"

volumes:
  db-volume:
