services:
  biss-ctf-back:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: biss-ctf-back:latest
    restart: always
    volumes:
      - type: bind
        source: "[ABSOLUTE_PATH]"
        target: /mnt/resources
    environment:
      SPRING_CONFIG_LOCATION: file:///mnt/resources/
#    Enable this for backend only
    ports:
      - "8080:8080"
  biss-ctf-front:
    build:
      context: ../ctf-front
      dockerfile: Dockerfile
    image: biss-ctf-front:latest
    restart: always
#    Enable this for frontend only
    ports:
      - "80:80"
