login:
  allowed-users:
    muhammad: DEVELOPMENT
    fatma: DEVOPS
    hamud: RESEARCH
    fuad: FIRMWARE
    osama: INTEGRATION
    noor: VALIDATION
    jamila: PLATFORM

routing:
  routing-paths:
    DEVELOPMENT:
      - LOGIN_WORDLE
      - GOOLOOG
      - PASSWORD_GAME
      - END_OF_CTF

password-game:
  values:
    minimum-password-length: 8
    biss-specific-words-list:
      - hufflepuff
      - gryffindor
      - slytherin
      - ravenclaw
    biss-number: 20
    biss-sponsor: olga
    sum-of-atomic-elements: 500
    roman-numeral-devisor: 35
    phrase-not-to-include: y8
    staff-total-height-in-cm: 1906
  descriptions:
    biss-specific-words: must include the best house in hogwarts
