login:
  allowed-users:
    muhammad: DEVELOPMENT
    fatma: DEVOPS
    hamud: RESEARCH
    fuad: FIRMWARE
    osama: INTEGRATION
    noor: VALIDATION
    jamila: PLATFORM

signal-chart:
  password-parts:
    - labane
    - shawarma
    - falafel
    - malawah
    - knafeh
    - hummus
    - zaatar
    - kebab
    - baklava
    - bamya
    - shakshukah
    - arayes
    - msabaha
    - matbuha
    - sabih
    - mejadra

routing:
  routing-paths:
    DEVELOPMENT:
      - LOGIN_WORDLE
      - GOOLOOG
      - PASSWORD_GAME
      - END_OF_CTF