name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ctf-backend:latest
    - name: Save the docker image
      run: docker save ctf-backend:latest -o backend.tar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: backend-image
        path: backend.tar
        if-no-files-found: error
        retention-days: 5
              
      
